export const lightTheme = {
  
  theme: "light",

  colors: {
    mainPurple: "#635FC7",
    mainPurpleHover: "#A8A4FF",
    black: "#000112",
    veryDarkGrey: "#20212C",
    darkGrey: "#2B2C37",
    linesDark: "#3E3F4E",
    mediumGrey: "#828FA3",
    linesLight: "#E4EBFA",
    lightGrey: "#F4F7FD",
    white: "#FFFFFF",
    red: "#EA5555",
    redHover: "#FF9898",
  },
  fonts: {
    heading_XL: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "24px",
      lineHeight: "30px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_L: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "18px",
      lineHeight: "23px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_M: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "15px",
      lineHeight: "19px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_S: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "12px",
      lineHeight: "15px",
      letterSpacing: "2.4px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
    body_M: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "12px",
      lineHeight: "15px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
    body_L: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "13px",
      lineHeight: "23px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
  },

  fromMobileS: "@media (min-width: 320px)",
  fromMobileM: "@media (min-width: 375px)",
  fromMobileL: "@media (min-width: 425px)",
  fromTabletSM: "@media (max-width: 576px)",
  fromTablet: "@media (min-width: 768px)",
  fromLaptop: "@media (min-width: 1024px)",
  fromLaptopL: "@media (min-width: 1440px)",
  fromDesktop: "@media (min-width: 2560px)",


  beforeMobileS: "@media (max-width: 320px)",
  beforeMobileM: "@media (max-width: 375px)",
  beforeMobileL: "@media (max-width: 425px)",
  fromTabletSM: "@media (max-width: 576px)",
  beforeTablet: "@media (max-width: 768px)",
  beforeLaptop: "@media (max-width: 1024px)",
  beforeLaptopL: "@media (max-width: 1440px)",
  beforeDesktop: "@media (max-width: 2560px)",
};

export const darkTheme = {

  theme: "dark",


  colors: {
    mainPurple: "#635FC7",
    mainPurpleHover: "#A8A4FF",
    black: "#000112",
    veryDarkGrey: "#20212C",
    darkGrey: "#2B2C37",
    linesDark: "#3E3F4E",
    mediumGrey: "#828FA3",
    linesLight: "#E4EBFA",
    lightGrey: "#F4F7FD",
    white: "#FFFFFF",
    red: "#EA5555",
    redHover: "#FF9898",
  },
  fonts: {
    heading_XL: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "24px",
      lineHeight: "30px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_L: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "18px",
      lineHeight: "23px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_M: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "15px",
      lineHeight: "19px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_S: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "12px",
      lineHeight: "15px",
      letterSpacing: "2.4px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
    body_M: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "12px",
      lineHeight: "15px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
    body_L: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "13px",
      lineHeight: "23px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
  },


  fromMobileS: "@media (min-width: 320px)",
  fromMobileM: "@media (min-width: 375px)",
  fromMobileL: "@media (min-width: 425px)",
  fromTabletSM: "@media (max-width: 600px)",
  fromTablet: "@media (min-width: 768px)",
  fromLaptop: "@media (min-width: 1024px)",
  fromLaptopL: "@media (min-width: 1440px)",
  fromDesktop: "@media (min-width: 2560px)",


  beforeMobileS: "@media (max-width: 320px)",
  beforeMobileM: "@media (max-width: 375px)",
  beforeMobileL: "@media (max-width: 425px)",
  fromTabletSM: "@media (max-width: 576px)",
  beforeTablet: "@media (max-width: 768px)",
  beforeLaptop: "@media (max-width: 1024px)",
  beforeLaptopL: "@media (max-width: 1440px)",
  beforeDesktop: "@media (max-width: 2560px)",
};