export const bazeTheme = {

  colors: {
    mainPurple: "#635FC7",
    mainPurpleHover: "#A8A4FF",
    black: "#000112",
    veryDarkGrey: "#20212C",
    darkGrey: "#2B2C37",
    linesDark: "#3E3F4E",
    mediumGrey: "#828FA3",
    linesLight: "#E4EBFA",
    lightGrey: "#F4F7FD",
    white: "#FFFFFF",
    red: "#EA5555",
    redHover: "#FF9898",
  },
  fonts: {
    heading_XL: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "24px",
      lineHeight: "30px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_L: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "18px",
      lineHeight: "23px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_M: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "15px",
      lineHeight: "19px",
      // color: '${props => props.theme.main.colors.black}',
    },
    heading_S: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "12px",
      lineHeight: "15px",
      letterSpacing: "2.4px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
    body_M: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: "12px",
      lineHeight: "15px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
    body_L: {
      fontFamily: "'Plus Jakarta Sans', sans-serif;",
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "13px",
      lineHeight: "23px",
      // color: '${props => props.theme.main.colors.mediumGrey}',
    },
  },

};